# Generated by Django 5.2 on 2025-06-03 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('STRIPE', 'Stripe')], max_length=50)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar'), ('GBP', 'Livre'), ('JPY', 'Yen'), ('CNY', 'Yuan'), ('RUB', 'Rouble'), ('INR', 'Roupie'), ('BRL', 'Real'), ('AUD', 'Dollar australien'), ('CAD', 'Dollar canadien'), ('CHF', 'Franc suisse'), ('NZD', 'Dollar néo-zélandais'), ('MXN', 'Peso mexicain'), ('AED', 'Dirham des Émirats'), ('ZAR', 'Rand sud-africain'), ('TRY', 'Lira turque'), ('PKR', 'Roupie pakistanaise'), ('XAF', 'Franc CFA (BEAC)'), ('XCD', 'Dollar des Caraïbes orientales'), ('XOF', 'Franc CFA (BCEAO)'), ('XPF', 'Franc Pacifique')], default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('EN COURS', 'En cours'), ('REUSSI', 'Réussi'), ('ECHOUE', 'Échoué')], default='EN COURS', max_length=20)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_time'],
            },
        ),
    ]
